đóng docker compose - bug hoài SOCKET HANG UP khi PING 3000 hoặc 25039   +++  Bug: XÁC THỰC GOOGLE GÌ ĐÓ LÀM CHO ĐÓNG DOCKER KHÔNG PING ĐƯỢC BACKEND
```
Vẫn bug: POST http://127.0.0.1:25039/chat
Error: socket hang up
Request Headers
Content-Type: application/json
User-Agent: PostmanRuntime/7.43.0
Accept: */*
Cache-Control: no-cache
Postman-Token: 91246568-07d1-4d86-8044-ef2e1d2e0853
Host: 127.0.0.1:25039
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Request Body

Check @backend
```

------

```bash
ed
backend-1   | 2024-12-19 15:45:06,912 - WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
backend-1   | 2024-12-19 15:45:08,990 - WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
backend-1   | 2024-12-19 15:45:08,991 - WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
backend-1   | Traceback (most recent call last):
backend-1   |   File "/app/app.py", line 70, in <module>
backend-1   |     initialize_components()
backend-1   |   File "/app/app.py", line 51, in initialize_components
backend-1   |     llm_handler = LLMHandler(
backend-1   |   File "/app/rag_pipeline/back.py", line 37, in __init__
backend-1   |     self.llm = ChatGoogleGenerativeAI(model=model_name, api_key=self.api_key)
backend-1   |   File "/usr/local/lib/python3.9/site-packages/langchain_core/load/serializable.py", line 125, in __init__
backend-1   |     super().__init__(*args, **kwargs)
backend-1   |   File "/usr/local/lib/python3.9/site-packages/pydantic/main.py", line 214, in __init__
backend-1   |     validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
backend-1   |   File "/usr/local/lib/python3.9/site-packages/langchain_google_genai/chat_models.py", line 838, in validate_environment
backend-1   |     self.client = genaix.build_generative_service(
backend-1   |   File "/usr/local/lib/python3.9/site-packages/langchain_google_genai/_genai_extension.py", line 276, in build_generative_service
backend-1   |     return v1betaGenerativeServiceClient(**config)
backend-1   |   File "/usr/local/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 687, in __init__
backend-1   |     self._transport = transport_init(
backend-1   |   File "/usr/local/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/transports/grpc.py", line 154, in __init__
backend-1   |     super().__init__(
backend-1   |   File "/usr/local/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/transports/base.py", line 100, in __init__
backend-1   |     credentials, _ = google.auth.default(
backend-1   |   File "/usr/local/lib/python3.9/site-packages/google/auth/_default.py", line 697, in default
backend-1   |     raise exceptions.DefaultCredentialsError(_CLOUD_SDK_MISSING_CREDENTIALS)
backend-1   | google.auth.exceptions.DefaultCredentialsError: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
backend-1 exited with code 0
backend-1   | /app/rag_pipeline/back.py:43: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-huggingface package and should be used instead. To use it run `pip install -U :class:`~langchain-huggingface` and import as `from :class:`~langchain_huggingface import HuggingFaceEmbeddings``.
backend-1   |   self.embeddings = HuggingFaceEmbeddings(model_name=model_name)
backend-1   | 2024-12-19 15:45:16,270 - INFO - 🔄 Initializing components...
backend-1   | 2024-12-19 15:45:16,445 - INFO - Use pytorch device_name: cpu
backend-1   | 2024-12-19 15:45:16,445 - INFO - Load pretrained SentenceTransformer: hiieu/halong_embedding
backend-1   | /app/rag_pipeline/back.py:56: LangChainDeprecationWarning: The class `Qdrant` was deprecated in LangChain 0.0.37 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-qdrant package and should be used instead. To use it run `pip install -U :class:`~langchain-qdrant` and import as `from :class:`~langchain_qdrant import Qdrant``.
backend-1   |   return Qdrant(
backend-1   | 2024-12-19 15:45:20,513 - INFO - ✅ Vector database initialized
backend-1   | 2024-12-19 15:45:20,520 - WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
backend-1   | 2024-12-19 15:45:21,528 - WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
backend-1   | 2024-12-19 15:45:23,501 - WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
backend-1   | 2024-12-19 15:45:23,501 - WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
backend-1   | Traceback (most recent call last):
backend-1   |   File "/app/app.py", line 70, in <module>
backend-1   |     initialize_components()
backend-1   |   File "/app/app.py", line 51, in initialize_components
backend-1   |     llm_handler = LLMHandler(
backend-1   |   File "/app/rag_pipeline/back.py", line 37, in __init__
backend-1   |     self.llm = ChatGoogleGenerativeAI(model=model_name, api_key=self.api_key)
backend-1   |   File "/usr/local/lib/python3.9/site-packages/langchain_core/load/serializable.py", line 125, in __init__
backend-1   |     super().__init__(*args, **kwargs)
backend-1   |   File "/usr/local/lib/python3.9/site-packages/pydantic/main.py", line 214, in __init__
backend-1   |     validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
backend-1   |   File "/usr/local/lib/python3.9/site-packages/langchain_google_genai/chat_models.py", line 838, in validate_environment
backend-1   |     self.client = genaix.build_generative_service(
backend-1   |   File "/usr/local/lib/python3.9/site-packages/langchain_google_genai/_genai_extension.py", line 276, in build_generative_service
backend-1   |     return v1betaGenerativeServiceClient(**config)
backend-1   |   File "/usr/local/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 687, in __init__
backend-1   |     self._transport = transport_init(
backend-1   |   File "/usr/local/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/transports/grpc.py", line 154, in __init__
backend-1   |     super().__init__(
backend-1   |   File "/usr/local/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/transports/base.py", line 100, in __init__
backend-1   |     credentials, _ = google.auth.default(
backend-1   |   File "/usr/local/lib/python3.9/site-packages/google/auth/_default.py", line 697, in default
backend-1   |     raise exceptions.DefaultCredentialsError(_CLOUD_SDK_MISSING_CREDENTIALS)
backend-1   | google.auth.exceptions.DefaultCredentialsError: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
backend-1 exited with code 0
backend-1   | /app/rag_pipeline/back.py:43: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-huggingface package and should be used instead. To use it run `pip install -U :class:`~langchain-huggingface` and import as `from :class:`~langchain_huggingface import HuggingFaceEmbeddings``.
backend-1   |   self.embeddings = HuggingFaceEmbeddings(model_name=model_name)
backend-1   | 2024-12-19 15:45:31,649 - INFO - 🔄 Initializing components...
backend-1   | 2024-12-19 15:45:31,842 - INFO - Use pytorch device_name: cpu
backend-1   | 2024-12-19 15:45:31,843 - INFO - Load pretrained SentenceTransformer: hiieu/halong_embedding

v View in Docker Desktop   o View Config   w Enable Watch
```

Bug: XÁC THỰC GOOGLE GÌ ĐÓ LÀM CHO ĐÓNG DOCKER KHÔNG PING ĐƯỢC BACKEND